/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as TrustedRouteImport } from './routes/trusted'
import { Route as ScansScanIdRouteImport } from './routes/scans.$scanId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustedRoute = TrustedRouteImport.update({
  id: '/trusted',
  path: '/trusted',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansScanIdRoute = ScansScanIdRouteImport.update({
  id: '/$scanId',
  path: '/$scanId',
  getParentRoute: () => ScansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/live': typeof LiveRoute
  '/scans': typeof ScansRouteWithChildren
  '/trusted': typeof TrustedRoute
  '/scans/$scanId': typeof ScansScanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/live': typeof LiveRoute
  '/scans': typeof ScansRouteWithChildren
  '/trusted': typeof TrustedRoute
  '/scans/$scanId': typeof ScansScanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/live': typeof LiveRoute
  '/scans': typeof ScansRouteWithChildren
  '/trusted': typeof TrustedRoute
  '/scans/$scanId': typeof ScansScanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analytics' | '/live' | '/scans' | '/trusted' | '/scans/$scanId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/live' | '/scans' | '/trusted' | '/scans/$scanId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/live'
    | '/scans'
    | '/trusted'
    | '/scans/$scanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LiveRoute: typeof LiveRoute
  ScansRoute: typeof ScansRouteWithChildren
  TrustedRoute: typeof TrustedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trusted': {
      id: '/trusted'
      path: '/trusted'
      fullPath: '/trusted'
      preLoaderRoute: typeof TrustedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$scanId': {
      id: '/scans/$scanId'
      path: '/$scanId'
      fullPath: '/scans/$scanId'
      preLoaderRoute: typeof ScansScanIdRouteImport
      parentRoute: typeof ScansRoute
    }
  }
}

interface ScansRouteChildren {
  ScansScanIdRoute: typeof ScansScanIdRoute
}

const ScansRouteChildren: ScansRouteChildren = {
  ScansScanIdRoute: ScansScanIdRoute,
}

const ScansRouteWithChildren = ScansRoute._addFileChildren(ScansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LiveRoute: LiveRoute,
  ScansRoute: ScansRouteWithChildren,
  TrustedRoute: TrustedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
